checking if the test works

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,30 +13,28 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12' # Замени на версию, которую используешь
-
-      - name: Install dependencies
+      - name: Build Docker image
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt # Если есть файл с зависимостями
+          docker build -t test-telegram-bot .
 
-      - name: Run Telegram Bot
+      - name: Run tests in temporary Docker container
         env:
-          BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }} # Добавь BOT_TOKEN в secrets репозитория
-          DATA_BASE_URL: ${{ secrets.DATA_BASE_URL }} # Добавь DATA_BASE_URL в secrets репозитория
+          BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
+          DATA_BASE_URL: ${{ secrets.DATA_BASE_URL }}
         run: |
-          python hookah_space_bot.py & # Запусти бота в фоне
-          sleep 10 # Подожди несколько секунд, чтобы бот подключился
-          ls -la /app/data/
-
-      - name: Check Bot is Running
-        run: |
-          if pgrep -f "hookah_space_bot.py"; then
-            echo "Bot is running successfully."
-          else
-            echo "Bot failed to start."
-            exit 1
-          fi
+          docker run --rm \
+            -e BOT_TOKEN=${BOT_TOKEN} \
+            -e DATA_BASE_URL=${DATA_BASE_URL} \
+            test-telegram-bot \
+            /bin/bash -c "
+              python -m pip install --upgrade pip && \
+              pip install -r requirements.txt && \
+              python hookah_space_bot.py & \
+              sleep 10 && \
+              if pgrep -f 'hookah_space_bot.py'; then
+                echo 'Bot is running successfully.';
+              else
+                echo 'Bot failed to start.';
+                exit 1;
+              fi
+            "
